# Generated by Django 3.0.6 on 2020-07-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptkeywords',
            options={'verbose_name_plural': 'scriptkeywords'},
        ),
    ]
