# Generated by Django 3.0.8 on 2020-08-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200808_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.Topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.Topic'),
            preserve_default=False,
        ),
    ]
