# Generated by Django 3.0.6 on 2020-07-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200728_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptkeywords',
            options={'verbose_name_plural': 'ScriptKeywords'},
        ),
    ]
