# Generated by Django 3.0.8 on 2020-08-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200808_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Topic'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Topic'),
        ),
    ]
