# Generated by Django 3.0.8 on 2020-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200808_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisobj',
            name='user',
        ),
        migrations.AlterField(
            model_name='analysisobj',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
