# Generated by Django 3.0.8 on 2020-08-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20200808_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='flags',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
