# Generated by Django 3.0.8 on 2020-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20200814_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='_flags',
            field=models.TextField(blank=True),
        ),
    ]
