# Generated by Django 3.0.8 on 2020-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_analysisobj_missed_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisobj',
            old_name='missed_words',
            new_name='highlights',
        ),
        migrations.AddField(
            model_name='analysisobj',
            name='highlights_hit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
