# Generated by Django 3.0.8 on 2020-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20200907_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisobj',
            name='filler_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
