# Generated by Django 3.0.8 on 2020-09-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_analysisobj_filler_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisobj',
            old_name='highlights_hit',
            new_name='highlights_missed',
        ),
    ]
