# Generated by Django 3.0.8 on 2020-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20200907_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.AddField(
            model_name='transcript',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
