# Generated by Django 3.0.8 on 2020-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20201228_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleaudiofile',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
