# Generated by Django 3.0.8 on 2020-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_simpleaudiofile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleaudiofile',
            name='original_transcription',
            field=models.TextField(null=True),
        ),
    ]
