# Generated by Django 3.0.8 on 2020-12-29 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_simpleaudiofile_original_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleaudiofile',
            old_name='audio',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='simpleaudiofile',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simpleaudiofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
